### ISSUE TITLE
Using SAP Event Mesh in multi tenant multi backend application

### ISSUE THREAD

**Issue by codeyogi911** [SAP-samples/partner-reference-application#9]
I was going through the application and was wondering if there is a way to subscribe events from multiple S4 systems in this application?

**Comment by knutheusermann** [comment]
The SAP Event Mesh can be used to realize event-based integrations between S/4HANA Cloud and single-tenant partner applications. You find an example on Github in the single-tenant version of the [partner reference application version 1](https://github.com/SAP-samples/sme-partner-reference-application) (using SAP Business ByDesign as ERP).
For partner-managed multitenant applications we are planning to realize event-based integrations with S/4HANA Cloud using the SAP Event Broker in the future. Follow our updates on the partner reference application version 2 for more information once the SAP Event Broker is available for partner-managed applications.

**Comment by codeyogi911** [comment]
@knutheusermann thanks but what should we use now? We are building a saas solution on BTP.
